export const SKILLS = [
  "JavaScript",
  "HTML",
  "CSS",
  "UI/UX Design",
  "React",
  "TypeScript",
  "GraphQL",
  "Python",
  "Pandas",
  "NumPy",
  "Vue.js",
  "Next.js",
  "Flask",
  "MongoDB",
  "PostgreSQL",
  "Express.js",
  "Node.js",
  "Bootstrap",
  "Docker",
  "Vite",
  "Redux",
  "REST APIs",
  "Figma",
  "Tailwind CSS",
  "Prototyping",
  "Design Systems",
  "HTML/CSS",
];

export const navItems = [
  { label: "Home", href: "/" },
  { label: "Explore", href: "/explore" },
];
