GET http://localhost:3000/api/users
###
GET http://localhost:3000/api/users?email=nhi.lpu1205@gmail.com

###
POST http://localhost:3000/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "email": "alexj"
}

###
DELETE  http://localhost:3000/api/users/685127985d5a26bb1be79a8e HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/users/685127985d5a26bb1be79a8e

###
POST http://localhost:3000/api/users/6839260a139193caf0fd2737/learning HTTP/1.1
Content-Type: application/json

{
    "skillId": "68383dacee97ee11c4c3af74"
}

###
DELETE  http://localhost:3000/api/users/6839260a139193caf0fd2737/learning HTTP/1.1
Content-Type: application/json

{
    "skillId": "68383dacee97ee11c4c3af74"
}

###
POST http://localhost:3000/api/users/6839260a139193caf0fd2737/teaching HTTP/1.1
Content-Type: application/json

{
    "skillId": "68383d72ee97ee11c4c3af72"
}

###
DELETE  http://localhost:3000/api/users/6839260a139193caf0fd2737/teaching HTTP/1.1
Content-Type: application/json

{
    "skillId": "68383d72ee97ee11c4c3af72"
}

###
PUT http://localhost:3000/api/users/6839260a139193caf0fd2737 HTTP/1.1
Content-Type: application/json

{
    "pfp": "/pfp/6839260a139193caf0fd2737.jpeg"
}
###
PUT http://localhost:3000/api/users/6839260a139193caf0fd2737 HTTP/1.1
Content-Type: application/json

{
    "password": "alexj"
}